{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pantrix.analytics",
    "module": "pantrix-gradle-plugin",
    "version": "1.0.0-beta.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantrix-gradle-plugin-1.0.0-beta.3.jar",
          "url": "pantrix-gradle-plugin-1.0.0-beta.3.jar",
          "size": 77427,
          "sha512": "f0215113df2a73cfd5b4f62ac4650fe3cb307dfc73b52977058d6c2c2dda78a3effe897d4fb251951dcf9d4de054e8536102a46019d32cd28a77a7294819a5d2",
          "sha256": "ea8ae0d2cafdbebf64d9814591a4b83490d525c2def21c319ba3fb4b8c6549c4",
          "sha1": "dbdbf3e1ef3b587f22862a6a2534cf0753e53b3e",
          "md5": "097c098311419f3eae58d8fe49ed0ffe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantrix-gradle-plugin-1.0.0-beta.3.jar",
          "url": "pantrix-gradle-plugin-1.0.0-beta.3.jar",
          "size": 77427,
          "sha512": "f0215113df2a73cfd5b4f62ac4650fe3cb307dfc73b52977058d6c2c2dda78a3effe897d4fb251951dcf9d4de054e8536102a46019d32cd28a77a7294819a5d2",
          "sha256": "ea8ae0d2cafdbebf64d9814591a4b83490d525c2def21c319ba3fb4b8c6549c4",
          "sha1": "dbdbf3e1ef3b587f22862a6a2534cf0753e53b3e",
          "md5": "097c098311419f3eae58d8fe49ed0ffe"
        }
      ]
    }
  ]
}
