{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pantrix.analytics",
    "module": "pantrix-feedback",
    "version": "1.0.0-alpha.01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantrix-feedback-1.0.0-alpha.01.aar",
          "url": "pantrix-feedback-1.0.0-alpha.01.aar",
          "size": 69150,
          "sha512": "481aba53e8c972b36c968e196210cc9b2943ff9de4d93817eb0206782e83cf00bc9816f861512407562ca9af55c6c5bd72cd6e2c688d34e3d80272d34ddc9644",
          "sha256": "f419f7f81ff39055fc405d6da61edd4abba47e4f26eaa38173f3c87cb1557b50",
          "sha1": "6093cd645aab67c4ab1bf9c8242b30054ad561cf",
          "md5": "a7b838b0ba9ba3df8a2fa58f0a6d5dc9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.01.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantrix-feedback-1.0.0-alpha.01.aar",
          "url": "pantrix-feedback-1.0.0-alpha.01.aar",
          "size": 69150,
          "sha512": "481aba53e8c972b36c968e196210cc9b2943ff9de4d93817eb0206782e83cf00bc9816f861512407562ca9af55c6c5bd72cd6e2c688d34e3d80272d34ddc9644",
          "sha256": "f419f7f81ff39055fc405d6da61edd4abba47e4f26eaa38173f3c87cb1557b50",
          "sha1": "6093cd645aab67c4ab1bf9c8242b30054ad561cf",
          "md5": "a7b838b0ba9ba3df8a2fa58f0a6d5dc9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantrix-feedback-1.0.0-alpha.01-javadoc.jar",
          "url": "pantrix-feedback-1.0.0-alpha.01-javadoc.jar",
          "size": 378855,
          "sha512": "993e005c466bfa836324f73fbc4f65e681bd13b287a878cd819325e85d666f29eef02399d3377ce5e6351c9cd7b193a6723fdf84e82b6ca03fd142c6c89e8f45",
          "sha256": "6fb383dfb18ee19213091e7e0ec42cfa75406d64b23a5d2d790b60c07059362f",
          "sha1": "fdce150b623d470af41a8ae5177beede9330783f",
          "md5": "4700b07d6514cfba966006c217615046"
        }
      ]
    }
  ]
}
