{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pantrix.analytics",
    "module": "pantrix-compose-navigation3",
    "version": "1.0.0-beta.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantrix-compose-navigation3-1.0.0-beta.9.aar",
          "url": "pantrix-compose-navigation3-1.0.0-beta.9.aar",
          "size": 5772,
          "sha512": "a9ed2482f3031915199fea1c8c0532bd64f5e3e2648a683a47d6a2cda6e78b4404935b2103d4b151639cdbca2d7a381c6e1abfb49963fc400f41905b04b1f11e",
          "sha256": "a1f45e414dfc58320210630cd2691ec21990a6b5285a505b0312a954ea86eacd",
          "sha1": "a75f3ee6fb0d34dc847d21d87f3e1d29966c46af",
          "md5": "105124d4f006ab8d6ccb845d75edbf0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantrix-compose-navigation3-1.0.0-beta.9.aar",
          "url": "pantrix-compose-navigation3-1.0.0-beta.9.aar",
          "size": 5772,
          "sha512": "a9ed2482f3031915199fea1c8c0532bd64f5e3e2648a683a47d6a2cda6e78b4404935b2103d4b151639cdbca2d7a381c6e1abfb49963fc400f41905b04b1f11e",
          "sha256": "a1f45e414dfc58320210630cd2691ec21990a6b5285a505b0312a954ea86eacd",
          "sha1": "a75f3ee6fb0d34dc847d21d87f3e1d29966c46af",
          "md5": "105124d4f006ab8d6ccb845d75edbf0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantrix-compose-navigation3-1.0.0-beta.9-javadoc.jar",
          "url": "pantrix-compose-navigation3-1.0.0-beta.9-javadoc.jar",
          "size": 260901,
          "sha512": "63b7ef6ff52c1f2d2937694f88291e33fd089105684bcc1d8b91ff081481552b7d2f8ea59e210a0df9af916b0cc99889a3d3e24c43eef51bf84943b6695643a9",
          "sha256": "3a2523c479d63f0012c8d085f81cddb80c52efe3ba502ddf07cea292add1f189",
          "sha1": "4226764d609818688fe1054a1ab874474f37383e",
          "md5": "58138e366e5c5ea69bba5ddb5e011946"
        }
      ]
    }
  ]
}
