{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pantrix.analytics",
    "module": "pantrix-gradle-plugin",
    "version": "1.0.0-beta.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantrix-gradle-plugin-1.0.0-beta.9.jar",
          "url": "pantrix-gradle-plugin-1.0.0-beta.9.jar",
          "size": 78380,
          "sha512": "35554e19c861203b10f29d952f6a90088425c9f0e12970e19237cf4a4dd77243eb4a90bd996b8546e9748e381134b3a413dcaec86fc4c349695502590c2ac923",
          "sha256": "d5cd156521840149ecbf4aad2a2c144860130b56dbdcb1fd6dfb31e29d71edda",
          "sha1": "4965ad84f524c14bfd12d436f0a36bf651afbe84",
          "md5": "c613d74fd645d0d6ba1781203dbcdbe1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantrix-gradle-plugin-1.0.0-beta.9.jar",
          "url": "pantrix-gradle-plugin-1.0.0-beta.9.jar",
          "size": 78380,
          "sha512": "35554e19c861203b10f29d952f6a90088425c9f0e12970e19237cf4a4dd77243eb4a90bd996b8546e9748e381134b3a413dcaec86fc4c349695502590c2ac923",
          "sha256": "d5cd156521840149ecbf4aad2a2c144860130b56dbdcb1fd6dfb31e29d71edda",
          "sha1": "4965ad84f524c14bfd12d436f0a36bf651afbe84",
          "md5": "c613d74fd645d0d6ba1781203dbcdbe1"
        }
      ]
    }
  ]
}
