{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pantrix.analytics",
    "module": "pantrix-compose-navigation3",
    "version": "1.0.0-alpha.01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantrix-compose-navigation3-1.0.0-alpha.01.aar",
          "url": "pantrix-compose-navigation3-1.0.0-alpha.01.aar",
          "size": 5772,
          "sha512": "a9ed2482f3031915199fea1c8c0532bd64f5e3e2648a683a47d6a2cda6e78b4404935b2103d4b151639cdbca2d7a381c6e1abfb49963fc400f41905b04b1f11e",
          "sha256": "a1f45e414dfc58320210630cd2691ec21990a6b5285a505b0312a954ea86eacd",
          "sha1": "a75f3ee6fb0d34dc847d21d87f3e1d29966c46af",
          "md5": "105124d4f006ab8d6ccb845d75edbf0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantrix-compose-navigation3-1.0.0-alpha.01.aar",
          "url": "pantrix-compose-navigation3-1.0.0-alpha.01.aar",
          "size": 5772,
          "sha512": "a9ed2482f3031915199fea1c8c0532bd64f5e3e2648a683a47d6a2cda6e78b4404935b2103d4b151639cdbca2d7a381c6e1abfb49963fc400f41905b04b1f11e",
          "sha256": "a1f45e414dfc58320210630cd2691ec21990a6b5285a505b0312a954ea86eacd",
          "sha1": "a75f3ee6fb0d34dc847d21d87f3e1d29966c46af",
          "md5": "105124d4f006ab8d6ccb845d75edbf0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pantrix-compose-navigation3-1.0.0-alpha.01-javadoc.jar",
          "url": "pantrix-compose-navigation3-1.0.0-alpha.01-javadoc.jar",
          "size": 260907,
          "sha512": "2029dd61d73707c10f95a23ab78843ba53e3a2002daf09e2d5d40f528b9aa0c827bf6a83404e7f3a508bd6c8a6e77941bb8cc81ce94806a59502a13dc11766c2",
          "sha256": "8b1d66bf70a8fd80de5d331f9a10fbd9ef161366668766c5ff05b09998b84876",
          "sha1": "216bd0cd07b83efa8ec08756de19ac928c6952bd",
          "md5": "54d55fc6f4a3de1c427f7ede5863e0cc"
        }
      ]
    }
  ]
}
